### ISSUE TITLE
Cannot generate graph in java for a long time

### ISSUE THREAD

**Issue by kunzeng-ch** [doxygen/doxygen#9490]
Hello! I used doxygen to analysis the java codes(log4j2). Howere, after waiting for a long time, no relevant files have been generated. There are only two files index.hhc and index.hhk in the html folder. Here are my codes and configuration file.
Source codes in the url: https://github.com/apache/logging-log4j2/tree/rel/2.17.2
Configuration: [log4j2.zip](https://github.com/doxygen/doxygen/files/9257678/log4j2.zip)

_Originally posted by @kunzeng-ch in https://github.com/doxygen/doxygen/issues/9486#issuecomment-1204891614_

**Comment by kunzeng-ch** [comment]
I am sorry for adding a url, here are the source codes.
[logging-log4j2-rel-2.17.2.zip](https://github.com/doxygen/doxygen/files/9258283/logging-log4j2-rel-2.17.2.zip)

**Comment by albert-github** [comment]
Some investigations have been done and reported as https://github.com/doxygen/doxygen/issues/9486#issuecomment-1204957426:

I did a quick test and under Windows it looks like doxygen goes into an endless loop (with the 1.9.4 version but also with the self build master, 1.9.5 (https://github.com/doxygen/doxygen/commit/5763255ba4fb02b7fa11300515f46fbfda38180e), version with "Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x64").
When I ran under Cygwin all looks to be OK

Seen the nature of the problem it is hard to prune the large example.

**Comment by kunzeng-ch** [comment]
OK! Thank you for your apply! Has this problem occurred before?

**Comment by albert-github** [comment]
To the best of my knowledge it didn't appear before (at least I have not seen this special problem, where doxygen looks like to be stuck at "Building directory list").

**Comment by kunzeng-ch** [comment]
I suddenly remembered that I also encountered this problem in the first half of last year. At the beginning, I remembered that it was because the memory was not enough. I expanded the memory(16G) to generate pictures. You can try this.

**Comment by albert-github** [comment]
To the best of my knowledge it didn't appear before (at least I have not seen this special problem, where doxygen looks like to be stuck at ").

I don't think that in this case it is a memory problem, but a fundamental problem.

**Comment by doxygen** [comment]
I tried to reproduce the problem but the run just finished fine (generating over 19000 dot images).

**Comment by albert-github** [comment]
@doxygen You see the same as I see under Cygwin. Problem looks like to be related to the length of the path + filename.
I'm looking into the directories already and one of the files that looks like to give a problem looks like to be:
```
logging-log4j2-rel-2.17.2/log4j-spring-cloud-config/log4j-spring-cloud-config-samples/log4j-spring-cloud-config-sample-application/src/main/java/org/apache/logging/log4j/spring/cloud/config/sample/utils/spring/SampleResponseErrorHandler.jav
a
```
together with the path that is in front of it it is 265 character long and probably under Windows there is still the 255 limit (unless some special settings are done).

I'm going to do another run wit a bit of a smaller path and report back.

**Comment by albert-github** [comment]
@doxygen 
Test done.
I replaced the `logging-log4j2-rel-2.17.2` with `a` and now the problem runs OK, it is now generating over 19000 images.

I've attached a minimal `Doxyfile` with settings used: [Doxyfile.tar.gz](https://github.com/doxygen/doxygen/files/9258866/Doxyfile.tar.gz)

Probably best solution would be that a warning is given when a path + filename exceeds a certain (system dependent) limit and that the file is excluded from further processing. Maybe you have an idea...
Problem will probably only surface with Java as it is known for its very long paths (other candidates might be Python and maybe C#).

**Comment by doxygen** [comment]
On Windows 10, the path limits can be removed via a registry setting it seems: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by albert-github** [comment]
This would indeed be a solution for people that have full control over there system (In a lot of companies users cannot change their system registry as they don't have sufficient privileges and / or it is forbidden by their IT deportment) and that are not faint at heart.
The problem remains that when it is not set doxygen will get stuck (like OP) and has no idea where to look, so some hint might be still in place to the user (I don't think a hanging system is nice).

**Comment by doxygen** [comment]
@albert-github I agree that user should not (have to) tinker with registry settings, and that doxygen should just ignore files it cannot read (or at least give a proper error).

Can you run a debug build of doxygen and attach a debugger when it hangs and do a stack trace?

**Comment by albert-github** [comment]
Unfortunately not, I don't have the full MSVC (GUI) enabled as for some strange reason Microsoft blocks my account I used for this. So I cannot get into the debugger.

**Comment by doxygen** [comment]
> Unfortunately not, I don't have the full MSVC (GUI) enabled as for some strange reason Microsoft blocks my account I used for this. So I cannot get into the debugger.

That's unfortunate, and would it work with Cygwin in combination with `gdb`?

**Comment by albert-github** [comment]
That is leaning out of the window quite far, but worth a try.

Had some problems with the path of the executable, but I could start gdb under windows (64-bit debug executable)
```
gdb doxygen.exe
GNU gdb (GDB) (Cygwin 11.2-1) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-cygwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from doxygen.exe...
(No debugging symbols found in doxygen.exe)
(gdb) run
Starting program: /cygdrive/d/speeltuin/issue_9490/doxygen.exe
[New Thread 7732.0x2e04]
[New Thread 7732.0x31c4]
[New Thread 7732.0x2a7c]
error: When enabling GENERATE_HTMLHELP the SEARCHENGINE option should be disabled. I'll adjust it for you.
error: When enabling GENERATE_HTMLHELP the HTML_DYNAMIC_MENUS option should be disabled. I'll adjust it for you.
Doxygen version used: 1.9.4 (db073db14ad01245252fa5179df8f2e1c7cf2750*)
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...

....

Building macro definition list...
Building group list...
Building directory list...
[New Thread 7732.0xb34]

Thread 5 received signal SIGINT, Interrupt.
[Switching to Thread 7732.0xb34]
Quit
(gdb) where
#0  0x00007ff7308376bc in ?? ()
#1  0x00007ff73084a184 in ?? ()
#2  0x00007ff7308397b4 in ?? ()
#3  0x00007ff7308c0072 in ?? ()
#4  0x00007ff7308b90ab in ?? ()
#5  0x00007ff730653240 in ?? ()
#6  0x00007ff73064e5b3 in ?? ()
#7  0x00007ff731934584 in ?? ()
#8  0x00007ff73193442e in ?? ()
#9  0x00007ff7319342ee in ?? ()
#10 0x00007ff731934619 in ?? ()
#11 0x00007ffefd657034 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/WINDOWS/System32/KERNEL32.DLL
#12 0x00007ffefe922651 in ntdll!RtlUserThreadStart () from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

So unfortunately no result.

(running under Cygwin didn't give a result either:
`=`
(gdb) where
#0  0x00007ffefc121b5d in TlsGetValue () from /cygdrive/c/WINDOWS/System32/KERNELBASE.dll
#1  0x00007ffefd657034 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/WINDOWS/System32/KERNEL32.DLL
#2  0x00007ffefe922651 in ntdll!RtlUserThreadStart () from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
#3  0x0000000000000000 in ?? ()

```
)

**Comment by kunzeng-ch** [comment]
Thank you very much! According to the link; https://github.com/doxygen/doxygen/issues/9490#issuecomment-1205071804, I need to shorten the path. Is it right？But there is a problem, such as calling functions between files, just like Python, that is to say, the file names in the code also need to be modified together, right?

**Comment by albert-github** [comment]
Shorting the path did help as a workaround in my case. There is no need to change file names, just changing directory names should be sufficient or seeing to it that initial path is short. It is all about the length of the path + the filename.

**Comment by kunzeng-ch** [comment]
OK! Firstly, I try to run doxygen in Ubuntu. If it is OK, I run it in Ubuntu
